import { FilterConfig } from '@/types/filters';

export const DOCTOR_FILTERS: FilterConfig[] = [
  {
    id: 'specialties',
    title: 'تخصص‌ها',
    label: 'تخصص مورد نظر را انتخاب کنید',
    options: [
      { id: 'general', label: 'پزشک عمومی' },
      { id: 'internal-medicine', label: 'داخلی' },
      { id: 'cardiology', label: 'قلب و عروق' },
      { id: 'pulmonology', label: 'ریه و دستگاه تنفسی' },
      { id: 'gastroenterology', label: 'گوارش و کبد' },
      { id: 'hepatology', label: 'هپاتولوژی (کبد)' },
      { id: 'nephrology', label: 'نفرولوژی (کلیه)' },
      { id: 'endocrinology', label: 'غدد و متابولیسم' },
      { id: 'diabetes', label: 'دیابت' },
      { id: 'thyroid', label: 'تیروئید' },
      { id: 'rheumatology', label: 'روماتولوژی' },
      { id: 'hematology', label: 'هماتولوژی (خون‌شناسی)' },
      { id: 'allergy-immunology', label: 'آلرژی و ایمونولوژی' },
      { id: 'infectious-disease', label: 'بیماری‌های عفونی و گرمسیری' },
      { id: 'neurology', label: 'مغز و اعصاب' },
      { id: 'psychiatry', label: 'روانپزشکی' },
      { id: 'psychology', label: 'روانشناسی' },
      { id: 'general-surgery', label: 'جراحی عمومی' },
      { id: 'neurosurgery', label: 'جراحی مغز و اعصاب' },
      { id: 'cardiac-surgery', label: 'جراحی قلب و عروق' },
      { id: 'orthopedics', label: 'ارتوپدی' },
      { id: 'plastic-surgery', label: 'جراحی پلاستیک و ترمیمی' },
      { id: 'vascular-surgery', label: 'جراحی عروق' },
      { id: 'thoracic-surgery', label: 'جراحی قفسه سینه' },
      { id: 'colorectal-surgery', label: 'جراحی کولون و رکتوم' },
      { id: 'pediatric-surgery', label: 'جراحی اطفال' },
      { id: 'oral-maxillofacial', label: 'جراحی فک و صورت' },
      { id: 'urology-surgery', label: 'جراحی کلیه و مجاری ادراری' },
      { id: 'gynecology', label: 'زنان و زایمان' },
      { id: 'infertility', label: 'ناباروری و IVF' },
      { id: 'pediatrics', label: 'کودکان (اطفال)' },
      { id: 'neonatology', label: 'نوزادان' },
      { id: 'urology', label: 'اورولوژی (ادراری و تناسلی)' },
      { id: 'dermatology', label: 'پوست، مو و زیبایی' },
      { id: 'ophthalmology', label: 'چشم‌پزشکی' },
      { id: 'ent', label: 'گوش، حلق و بینی' },
      { id: 'oncology', label: 'انکولوژی (سرطان‌شناسی)' },
      { id: 'radiation-oncology', label: 'رادیوتراپی (پرتودرمانی)' },
      { id: 'hematology-oncology', label: 'خون و سرطان' },
      { id: 'radiology', label: 'رادیولوژی' },
      { id: 'sonography', label: 'سونوگرافی' },
      { id: 'mri', label: 'ام آر آی' },
      { id: 'ct-scan', label: 'سی تی اسکن' },
      { id: 'nuclear-medicine', label: 'طب هسته‌ای' },
      { id: 'pathology', label: 'پاتولوژی' },
      { id: 'physical-medicine', label: 'طب فیزیکی و توانبخشی' },
      { id: 'physiotherapy', label: 'فیزیوتراپی' },
      { id: 'occupational-therapy', label: 'کاردرمانی' },
      { id: 'speech-therapy', label: 'گفتاردرمانی' },
      { id: 'dentistry', label: 'دندانپزشکی عمومی' },
      { id: 'orthodontics', label: 'ارتودنسی' },
      { id: 'periodontics', label: 'پریودنتیکس (لثه)' },
      { id: 'endodontics', label: 'اندودنتیکس (عصب‌کشی)' },
      { id: 'dental-prosthetics', label: 'پروتزهای دندانی' },
      { id: 'oral-radiology', label: 'رادیولوژی دهان و فک' },
      { id: 'pediatric-dentistry', label: 'دندانپزشکی کودکان' },
      { id: 'dental-surgery', label: 'جراحی دهان و دندان' },
      { id: 'cosmetic-dentistry', label: 'دندانپزشکی زیبایی' },
      { id: 'sports-medicine', label: 'طب ورزشی' },
      { id: 'occupational-medicine', label: 'طب کار' },
      { id: 'emergency-medicine', label: 'طب اورژانس' },
      { id: 'geriatrics', label: 'طب سالمندان' },
      { id: 'blood-transfusion', label: 'طب انتقال خون' },
      { id: 'genetics', label: 'ژنتیک پزشکی' },
      { id: 'forensic-medicine', label: 'پزشکی قانونی' },
      { id: 'traditional-medicine', label: 'طب سنتی ایرانی' },
      { id: 'acupuncture', label: 'طب سوزنی' },
      { id: 'homeopathy', label: 'هومیوپاتی' },
    ],
  },
  {
    id: 'insurances',
    title: 'بیمه',
    label: 'بیمه مورد نظر را انتخاب کنید',
    options: [
      { id: 'iran', label: 'ایران' },
      { id: 'tamin', label: 'تامین اجتماعی' },
      { id: 'azar', label: 'آذر' },
      { id: 'alborz', label: 'البرز' },
      { id: 'mellat', label: 'ملت' },
      { id: 'saman', label: 'سامان' },
      { id: 'ayandeh', label: 'آینده' },
      { id: 'tejarat', label: 'تجارت' },
      { id: 'dana', label: 'دانا' },
      { id: 'armed-forces', label: 'نیروهای مسلح' },
    ],
  },
  {
    id: 'experience',
    title: 'تجربه کاری',
    label: 'حداقل سابقه',
    options: [
      { id: '5+', label: '۵ سال به بالا' },
      { id: '10+', label: '۱۰ سال به بالا' },
      { id: '15+', label: '۱۵ سال به بالا' },
    ],
  },
  {
    id: 'availability',
    title: 'وضعیت نوبت دهی',
    label: 'وضعیت مورد نظر را انتخاب کنید',
    options: [
      { id: 'available-today', label: 'پزشکان دارای نوبت خالی' },
      { id: 'weekend', label: 'امکان رزرو در روزهای تعطیل' },
      { id: 'evening', label: 'نوبت عصر و شب' },
      { id: 'online-visit', label: 'ویزیت آنلاین' },
    ],
  },
];
